require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');
const { getDb } = require('../database');

async function addModules(db, courseId, modules) {
  const ids = [];
  for (const m of modules) {
    const mid = uuidv4();
    ids.push(mid);
    await db.run('INSERT INTO modules (id, course_id, title, content, order_index, duration_minutes) VALUES (?, ?, ?, ?, ?, ?)',
      [mid, courseId, m.title, m.content, m.order_index, m.duration_minutes]);
  }
  return ids;
}

async function addAssignment(db, moduleId, courseId, title, description, instructions) {
  await db.run('INSERT INTO assignments (id, module_id, course_id, title, description, instructions, due_days) VALUES (?, ?, ?, ?, ?, ?, ?)',
    [uuidv4(), moduleId, courseId, title, description, instructions, 7]);
}

async function addQuizzes(db, quizzes) {
  for (const q of quizzes) {
    await db.run('INSERT INTO quizzes (id, module_id, question, options, correct_answer, explanation) VALUES (?, ?, ?, ?, ?, ?)',
      [uuidv4(), q.moduleId, q.question, JSON.stringify(q.options), q.correct, q.explanation]);
  }
}

async function seedData(db) {
  const hashedPw = await bcrypt.hash('password123', 12);
  const adminId = uuidv4(), youth1Id = uuidv4(), youth2Id = uuidv4(), employer1Id = uuidv4(), employer2Id = uuidv4();

  const insertUser = async (id, name, email, role, bio, location, skills) => {
    await db.run('INSERT INTO users (id, name, email, password, role, bio, location, skills) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
      [id, name, email, hashedPw, role, bio, location, JSON.stringify(skills)]);
  };

  await insertUser(adminId, 'Admin User', 'admin@youthskills.com', 'admin', 'Platform administrator', 'Nairobi, Kenya', []);
  await insertUser(youth1Id, 'Amara Osei', 'amara@example.com', 'youth', 'Passionate about technology and design', 'Accra, Ghana', ['HTML', 'CSS', 'Figma']);
  await insertUser(youth2Id, 'Kwame Mensah', 'kwame@example.com', 'youth', 'Aspiring entrepreneur and developer', 'Lagos, Nigeria', ['JavaScript', 'Business Planning']);
  await insertUser(employer1Id, 'TechAfrica Ltd', 'hr@techafrica.com', 'employer', 'Leading tech company in Africa', 'Nairobi, Kenya', []);
  await insertUser(employer2Id, 'Creative Hub', 'jobs@creativehub.com', 'employer', 'Creative agency for digital content', 'Accra, Ghana', []);

  const courses = [
    { id: uuidv4(), title: 'Introduction to Web Development', category: 'coding', level: 'beginner', description: 'Learn the fundamentals of HTML, CSS, and JavaScript to build your first website. This course covers everything from basic structure to interactive web pages.', duration_hours: 20, instructor_name: 'Allan Dabali', instructor_bio: 'Digital Skills Trainer & Platform Director, YouthSkills Program', thumbnail: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400', tags: ['HTML', 'CSS', 'JavaScript', 'Web'] },
    { id: uuidv4(), title: 'Graphic Design Fundamentals', category: 'design', level: 'beginner', description: 'Master the principles of graphic design including color theory, typography, layout, and branding. Create stunning visuals using industry-standard tools.', duration_hours: 15, instructor_name: 'Allan Dabali', instructor_bio: 'Digital Skills Trainer & Platform Director, YouthSkills Program', thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400', tags: ['Design', 'Figma', 'Branding', 'Typography'] },
    { id: uuidv4(), title: 'Entrepreneurship & Business Basics', category: 'entrepreneurship', level: 'beginner', description: 'Discover how to turn your ideas into a successful business. Learn business planning, market research, financial basics, and pitching to investors.', duration_hours: 12, instructor_name: 'Allan Dabali', instructor_bio: 'Digital Skills Trainer & Platform Director, YouthSkills Program', thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', tags: ['Business', 'Startup', 'Finance', 'Marketing'] },
    { id: uuidv4(), title: 'Python Programming for Beginners', category: 'coding', level: 'beginner', description: 'Start your programming journey with Python. Learn variables, loops, functions, and build real projects.', duration_hours: 25, instructor_name: 'Allan Dabali', instructor_bio: 'Digital Skills Trainer & Platform Director, YouthSkills Program', thumbnail: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400', tags: ['Python', 'Programming', 'Data', 'Automation'] },
    { id: uuidv4(), title: 'Digital Marketing Essentials', category: 'marketing', level: 'beginner', description: 'Learn how to grow businesses online through social media marketing, SEO, email campaigns, and content strategy.', duration_hours: 10, instructor_name: 'Allan Dabali', instructor_bio: 'Digital Skills Trainer & Platform Director, YouthSkills Program', thumbnail: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=400', tags: ['Marketing', 'Social Media', 'SEO', 'Content'] },
    { id: uuidv4(), title: 'Data Analysis with Excel & Google Sheets', category: 'data', level: 'beginner', description: 'Unlock the power of data analysis using spreadsheet tools. Learn formulas, pivot tables, charts, and data insights.', duration_hours: 8, instructor_name: 'Allan Dabali', instructor_bio: 'Digital Skills Trainer & Platform Director, YouthSkills Program', thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400', tags: ['Data', 'Excel', 'Analytics', 'Visualization'] },
  ];

  for (const c of courses) {
    await db.run('INSERT INTO courses (id, title, description, category, level, duration_hours, thumbnail, instructor_name, instructor_bio, tags) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
      [c.id, c.title, c.description, c.category, c.level, c.duration_hours, c.thumbnail, c.instructor_name, c.instructor_bio, JSON.stringify(c.tags)]);
  }

  // ── COURSE 1: Web Development ──────────────────────────────────────────────
  const webIds = await addModules(db, courses[0].id, [
    { title: 'HTML Basics', order_index: 1, duration_minutes: 45, content: 'HTML BASICS\n\nHTML (HyperText Markup Language) is the foundation of every web page.\n\nWHAT YOU WILL LEARN:\n- HTML document structure\n- Common tags: headings, paragraphs, links, images\n- Forms and input elements\n- Semantic HTML5 elements\n\nYOUR FIRST HTML PAGE:\n\n<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>My First Page</title>\n</head>\n<body>\n  <h1>Hello, World!</h1>\n  <p>Welcome to web development!</p>\n  <a href="https://google.com">Visit Google</a>\n</body>\n</html>\n\nKEY TAGS:\n- <h1> to <h6>: Headings\n- <p>: Paragraph\n- <a href="">: Link\n- <img src="" alt="">: Image\n- <div>: Container\n- <ul><li>: List\n- <form><input>: Form elements\n\nSemantic tags like <header>, <nav>, <main>, <footer> help describe the purpose of content to browsers and search engines.' },
    { title: 'CSS Styling', order_index: 2, duration_minutes: 60, content: 'CSS STYLING\n\nCSS (Cascading Style Sheets) controls how HTML looks.\n\nCORE CONCEPTS:\n- Selectors: target HTML elements\n- Properties: what to change\n- Values: how to change it\n\nBASIC SYNTAX:\nelement { property: value; }\n\nEXAMPLES:\n\nbody {\n  font-family: Arial, sans-serif;\n  background-color: #f0f0f0;\n  margin: 0;\n  padding: 20px;\n}\n\nh1 {\n  color: #2563eb;\n  font-size: 2rem;\n  text-align: center;\n}\n\n.card {\n  background: white;\n  border-radius: 8px;\n  padding: 20px;\n  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n}\n\nBOX MODEL:\nEvery element has: margin > border > padding > content\n\nFLEXBOX:\n.container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  gap: 16px;\n}\n\nRESPONSIVE DESIGN:\n@media (max-width: 768px) {\n  .card { padding: 10px; }\n}' },
    { title: 'JavaScript Fundamentals', order_index: 3, duration_minutes: 90, content: 'JAVASCRIPT FUNDAMENTALS\n\nJavaScript makes web pages interactive.\n\nVARIABLES:\nconst name = "Allan";  // cannot change\nlet age = 25;          // can change\n\nDATA TYPES:\n- String: "Hello"\n- Number: 42\n- Boolean: true / false\n- Array: [1, 2, 3]\n- Object: { name: "Allan", age: 25 }\n\nFUNCTIONS:\nfunction greet(name) {\n  return "Hello, " + name;\n}\n\n// Arrow function\nconst greet = (name) => "Hello, " + name;\n\nDOM MANIPULATION:\nconst btn = document.querySelector("#myBtn");\nconst title = document.querySelector("h1");\n\nbtn.addEventListener("click", () => {\n  title.textContent = "Button was clicked!";\n  title.style.color = "red";\n});\n\nFETCH API (get data from internet):\nasync function getData() {\n  const response = await fetch("https://api.example.com/data");\n  const data = await response.json();\n  console.log(data);\n}\n\ngetData();' },
  ]);
  await addQuizzes(db, [
    { moduleId: webIds[0], question: 'What does HTML stand for?', options: ['HyperText Markup Language', 'High Tech Modern Language', 'HyperText Modern Links', 'Home Tool Markup Language'], correct: 0, explanation: 'HTML stands for HyperText Markup Language.' },
    { moduleId: webIds[0], question: 'Which tag creates the largest heading?', options: ['<h6>', '<heading>', '<h1>', '<head>'], correct: 2, explanation: '<h1> is the largest heading. Headings go from h1 (largest) to h6 (smallest).' },
    { moduleId: webIds[1], question: 'Which CSS property changes text color?', options: ['font-color', 'text-color', 'color', 'foreground'], correct: 2, explanation: 'The "color" property in CSS sets the text color.' },
    { moduleId: webIds[1], question: 'What does CSS stand for?', options: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style System', 'Colorful Style Sheets'], correct: 1, explanation: 'CSS stands for Cascading Style Sheets.' },
    { moduleId: webIds[2], question: 'Which keyword declares a constant in JavaScript?', options: ['var', 'let', 'const', 'define'], correct: 2, explanation: '"const" declares a variable that cannot be reassigned.' },
    { moduleId: webIds[2], question: 'Which method adds an event listener in JavaScript?', options: ['addEvent()', 'addEventListener()', 'onEvent()', 'listenTo()'], correct: 1, explanation: 'addEventListener() attaches an event handler to an element.' },
  ]);

  // ── COURSE 2: Graphic Design ───────────────────────────────────────────────
  const designIds = await addModules(db, courses[1].id, [
    { title: 'Design Principles', order_index: 1, duration_minutes: 50, content: 'DESIGN PRINCIPLES\n\nGood design follows core principles that make visuals effective and beautiful.\n\nTHE 5 CORE PRINCIPLES:\n\n1. CONTRAST\nUse differences in color, size, or shape to make elements stand out.\nExample: Dark text on light background is easy to read.\n\n2. ALIGNMENT\nEvery element should be aligned with something else on the page.\nThis creates order and professionalism.\n\n3. REPETITION\nRepeat visual elements (colors, fonts, shapes) throughout your design.\nThis creates consistency and brand identity.\n\n4. PROXIMITY\nGroup related items together. Separate unrelated items.\nThis helps viewers understand relationships between content.\n\n5. WHITE SPACE\nEmpty space is not wasted space. It gives designs room to breathe.\nDo not crowd elements together.\n\nCOLOR THEORY:\n- Primary colors: Red, Blue, Yellow\n- Complementary colors: Opposite on color wheel (creates contrast)\n- Analogous colors: Next to each other (creates harmony)\n- Warm colors: Red, Orange, Yellow (energetic, exciting)\n- Cool colors: Blue, Green, Purple (calm, professional)\n\nTYPOGRAPHY BASICS:\n- Use maximum 2-3 fonts per design\n- Serif fonts (Times New Roman): formal, traditional\n- Sans-serif fonts (Arial, Helvetica): modern, clean\n- Font size hierarchy: Title > Heading > Body > Caption' },
    { title: 'Color Theory & Typography', order_index: 2, duration_minutes: 45, content: 'COLOR THEORY AND TYPOGRAPHY\n\nCOLOR PSYCHOLOGY:\nColors trigger emotions and associations.\n\n- RED: Energy, urgency, passion (used by Coca-Cola, YouTube)\n- BLUE: Trust, calm, professionalism (used by Facebook, LinkedIn)\n- GREEN: Nature, health, growth (used by WhatsApp, Spotify)\n- YELLOW: Happiness, optimism, warning (used by McDonald\'s)\n- BLACK: Luxury, sophistication, power (used by Apple, Nike)\n- WHITE: Cleanliness, simplicity, space\n- ORANGE: Creativity, enthusiasm, warmth (used by Amazon)\n\nCREATING A COLOR PALETTE:\n1. Choose a primary brand color\n2. Pick 1-2 complementary or analogous colors\n3. Add neutral colors (white, grey, black)\n4. Test for accessibility (enough contrast)\n\nTYPOGRAPHY IN DEPTH:\n\nFONT PAIRING RULES:\n- Pair a serif with a sans-serif\n- Use one font for headings, another for body\n- Keep it simple - less is more\n\nGOOD FONT PAIRS:\n- Playfair Display + Lato\n- Merriweather + Open Sans\n- Montserrat + Georgia\n\nTEXT HIERARCHY:\n- H1 Title: 36-48px, Bold\n- H2 Heading: 24-32px, Semi-bold\n- Body text: 16-18px, Regular\n- Caption: 12-14px, Light\n\nLINE SPACING: Use 1.5x the font size for comfortable reading.' },
    { title: 'Branding & Logo Design', order_index: 3, duration_minutes: 60, content: 'BRANDING AND LOGO DESIGN\n\nWHAT IS A BRAND?\nA brand is more than a logo. It is the complete experience and perception of a company.\n\nBRAND ELEMENTS:\n1. Logo - visual symbol\n2. Color palette - consistent colors\n3. Typography - consistent fonts\n4. Voice/Tone - how you communicate\n5. Values - what you stand for\n\nTYPES OF LOGOS:\n1. WORDMARK: Company name in stylized text (Google, Coca-Cola)\n2. LETTERMARK: Initials only (IBM, HBO, CNN)\n3. SYMBOL/ICON: Abstract or pictorial mark (Apple, Twitter)\n4. COMBINATION MARK: Icon + text (Nike, Adidas)\n5. EMBLEM: Text inside a symbol (Starbucks, Harley-Davidson)\n\nLOGO DESIGN PROCESS:\n1. Research the brand and competitors\n2. Sketch multiple concepts (at least 10)\n3. Choose the best 3 and refine digitally\n4. Test in different sizes and backgrounds\n5. Present to client with rationale\n\nLOGO DESIGN RULES:\n- Must work in black and white\n- Must be scalable (small and large)\n- Must be simple and memorable\n- Must be appropriate for the industry\n- Must be unique and original\n\nTOOLS FOR LOGO DESIGN:\n- Figma (free, web-based)\n- Adobe Illustrator (professional)\n- Canva (beginner-friendly)' },
  ]);
  await addQuizzes(db, [
    { moduleId: designIds[0], question: 'Which design principle involves grouping related items together?', options: ['Contrast', 'Alignment', 'Proximity', 'Repetition'], correct: 2, explanation: 'Proximity means grouping related items together to show their relationship.' },
    { moduleId: designIds[0], question: 'What are the primary colors?', options: ['Red, Green, Blue', 'Red, Blue, Yellow', 'Cyan, Magenta, Yellow', 'Orange, Purple, Green'], correct: 1, explanation: 'The traditional primary colors are Red, Blue, and Yellow.' },
    { moduleId: designIds[1], question: 'Which color is associated with trust and professionalism?', options: ['Red', 'Yellow', 'Blue', 'Orange'], correct: 2, explanation: 'Blue is associated with trust, calm, and professionalism - used by Facebook and LinkedIn.' },
    { moduleId: designIds[2], question: 'What type of logo uses only the company initials?', options: ['Wordmark', 'Lettermark', 'Symbol', 'Emblem'], correct: 1, explanation: 'A lettermark logo uses only the initials of the company name, like IBM or CNN.' },
  ]);

  // ── COURSE 3: Entrepreneurship ─────────────────────────────────────────────
  const bizIds = await addModules(db, courses[2].id, [
    { title: 'Finding Your Business Idea', order_index: 1, duration_minutes: 40, content: 'FINDING YOUR BUSINESS IDEA\n\nEvery successful business starts with solving a problem.\n\nHOW TO FIND A GOOD BUSINESS IDEA:\n\n1. IDENTIFY PROBLEMS YOU FACE\nWhat frustrates you daily? What takes too long? What is too expensive?\nExample: "There is no affordable food delivery in my area" → Start a local delivery service.\n\n2. LOOK AT YOUR SKILLS\nWhat are you good at? What do people ask you for help with?\nExample: Good at design → Offer freelance design services.\n\n3. SPOT MARKET GAPS\nWhat products or services are missing in your community?\nExample: No coding school for kids in your city → Start one.\n\n4. IMPROVE EXISTING SOLUTIONS\nCan you do something better, cheaper, or faster than what exists?\n\nTHE BUSINESS IDEA VALIDATION TEST:\nBefore investing time and money, ask:\n- Is there a real problem being solved?\n- Are people willing to PAY for this solution?\n- Is the market big enough?\n- Can you realistically build this?\n\nTYPES OF BUSINESSES:\n- Product business: Sell physical or digital products\n- Service business: Sell your skills and time\n- Platform business: Connect buyers and sellers\n- Subscription business: Charge recurring fees\n\nACTION STEP:\nWrite down 5 problems you have noticed in your community. For each one, think of a business that could solve it.' },
    { title: 'Business Planning Basics', order_index: 2, duration_minutes: 55, content: 'BUSINESS PLANNING BASICS\n\nA business plan is your roadmap to success.\n\nWHY YOU NEED A BUSINESS PLAN:\n- Clarifies your vision\n- Helps you get funding\n- Guides your decisions\n- Identifies potential problems early\n\nKEY SECTIONS OF A BUSINESS PLAN:\n\n1. EXECUTIVE SUMMARY\nA 1-page overview of your entire business.\nInclude: What you do, who you serve, your goal.\n\n2. PROBLEM AND SOLUTION\nClearly describe the problem and how your business solves it.\n\n3. TARGET MARKET\nWho are your customers?\n- Demographics: Age, gender, location, income\n- Psychographics: Interests, values, behavior\n- Market size: How many potential customers exist?\n\n4. PRODUCTS/SERVICES\nWhat exactly are you selling? What makes it unique?\n\n5. REVENUE MODEL\nHow will you make money?\n- Direct sales\n- Subscription fees\n- Commission\n- Advertising\n- Freemium (free + paid premium)\n\n6. MARKETING STRATEGY\nHow will customers find you?\n- Social media\n- Word of mouth\n- Partnerships\n- Advertising\n\n7. FINANCIAL PROJECTIONS\nEstimate your costs and expected revenue for Year 1.\n\nSTARTUP COSTS TO CONSIDER:\n- Equipment and tools\n- Marketing and advertising\n- Legal registration\n- Website and technology\n- Initial inventory' },
    { title: 'Marketing & Growing Your Business', order_index: 3, duration_minutes: 50, content: 'MARKETING AND GROWING YOUR BUSINESS\n\nMarketing is how you attract and keep customers.\n\nTHE MARKETING FUNNEL:\n1. AWARENESS: People learn you exist\n2. INTEREST: They want to know more\n3. CONSIDERATION: They compare you to competitors\n4. PURCHASE: They buy from you\n5. LOYALTY: They come back and refer others\n\nDIGITAL MARKETING CHANNELS:\n\n1. SOCIAL MEDIA MARKETING\n- Instagram: Visual products, lifestyle brands\n- Facebook: Broad audience, ads, groups\n- TikTok: Young audience, viral content\n- LinkedIn: B2B, professional services\n- Twitter/X: News, tech, conversations\n\n2. CONTENT MARKETING\nCreate valuable content that attracts customers.\n- Blog posts\n- YouTube videos\n- Podcasts\n- Free guides and ebooks\n\n3. EMAIL MARKETING\nBuild an email list and send regular updates.\nEmail has the highest ROI of any marketing channel.\n\n4. WORD OF MOUTH\nHappy customers are your best marketers.\nAsk for reviews and referrals.\n\nPRICING STRATEGIES:\n- Cost-plus: Add profit margin to your costs\n- Competitive: Match or beat competitor prices\n- Value-based: Charge what customers think it is worth\n- Freemium: Free basic, paid premium\n\nGROWTH TIPS:\n- Focus on customer satisfaction first\n- Reinvest profits back into the business\n- Build partnerships with complementary businesses\n- Track your numbers (revenue, costs, profit)' },
  ]);
  await addQuizzes(db, [
    { moduleId: bizIds[0], question: 'What is the most important first step when validating a business idea?', options: ['Build the product', 'Check if people will pay for it', 'Register the company', 'Hire employees'], correct: 1, explanation: 'Before investing time and money, you must confirm people are willing to pay for your solution.' },
    { moduleId: bizIds[1], question: 'What is the purpose of an Executive Summary in a business plan?', options: ['Detailed financial projections', 'A 1-page overview of the entire business', 'List of employees', 'Marketing budget'], correct: 1, explanation: 'The Executive Summary is a concise 1-page overview of your entire business plan.' },
    { moduleId: bizIds[2], question: 'Which marketing channel has the highest return on investment (ROI)?', options: ['Social media ads', 'TV commercials', 'Email marketing', 'Billboard ads'], correct: 2, explanation: 'Email marketing consistently delivers the highest ROI of any marketing channel.' },
  ]);

  // ── COURSE 4: Python Programming ───────────────────────────────────────────
  const pyIds = await addModules(db, courses[3].id, [
    { title: 'Python Basics', order_index: 1, duration_minutes: 60, content: 'PYTHON BASICS\n\nPython is one of the most popular programming languages in the world.\nIt is used for web development, data science, AI, and automation.\n\nWHY PYTHON?\n- Easy to read and write\n- Huge community and libraries\n- Used by Google, Netflix, Instagram\n- Great for beginners\n\nYOUR FIRST PYTHON PROGRAM:\nprint("Hello, World!")\n\nVARIABLES:\nname = "Allan"\nage = 25\nheight = 5.9\nis_student = True\n\nprint(name)    # Output: Allan\nprint(age)     # Output: 25\n\nDATA TYPES:\n- str: Text ("Hello")\n- int: Whole numbers (25)\n- float: Decimal numbers (5.9)\n- bool: True or False\n- list: [1, 2, 3]\n- dict: {"name": "Allan", "age": 25}\n\nBASIC OPERATIONS:\nprint(10 + 5)   # 15\nprint(10 - 3)   # 7\nprint(10 * 2)   # 20\nprint(10 / 3)   # 3.333\nprint(10 // 3)  # 3 (floor division)\nprint(10 % 3)   # 1 (remainder)\n\nUSER INPUT:\nname = input("What is your name? ")\nprint("Hello, " + name + "!")\n\nSTRING METHODS:\ntext = "hello world"\nprint(text.upper())       # HELLO WORLD\nprint(text.capitalize())  # Hello world\nprint(text.replace("world", "Python"))  # hello Python\nprint(len(text))          # 11' },
    { title: 'Control Flow & Functions', order_index: 2, duration_minutes: 70, content: 'CONTROL FLOW AND FUNCTIONS\n\nIF STATEMENTS:\nage = 18\n\nif age >= 18:\n    print("You are an adult")\nelif age >= 13:\n    print("You are a teenager")\nelse:\n    print("You are a child")\n\nLOOPS:\n\n# For loop\nfor i in range(5):\n    print(i)  # prints 0, 1, 2, 3, 4\n\n# Loop through a list\nfruits = ["apple", "banana", "mango"]\nfor fruit in fruits:\n    print(fruit)\n\n# While loop\ncount = 0\nwhile count < 5:\n    print(count)\n    count += 1\n\nLISTS:\nnumbers = [1, 2, 3, 4, 5]\nnumbers.append(6)      # Add to end\nnumbers.remove(3)      # Remove value\nprint(numbers[0])      # First item: 1\nprint(numbers[-1])     # Last item: 6\nprint(len(numbers))    # Length: 5\n\nDICTIONARIES:\nstudent = {\n    "name": "Amara",\n    "age": 20,\n    "course": "Python"\n}\nprint(student["name"])  # Amara\nstudent["grade"] = "A"  # Add new key\n\nFUNCTIONS:\ndef greet(name):\n    return "Hello, " + name + "!"\n\nresult = greet("Kwame")\nprint(result)  # Hello, Kwame!\n\n# Function with default parameter\ndef power(base, exponent=2):\n    return base ** exponent\n\nprint(power(3))     # 9\nprint(power(2, 3))  # 8' },
    { title: 'Python Projects', order_index: 3, duration_minutes: 80, content: 'PYTHON PROJECTS\n\nLet us build real projects to practice what we have learned.\n\nPROJECT 1: SIMPLE CALCULATOR\n\ndef calculator():\n    print("Simple Calculator")\n    num1 = float(input("Enter first number: "))\n    operator = input("Enter operator (+, -, *, /): ")\n    num2 = float(input("Enter second number: "))\n\n    if operator == "+":\n        result = num1 + num2\n    elif operator == "-":\n        result = num1 - num2\n    elif operator == "*":\n        result = num1 * num2\n    elif operator == "/":\n        if num2 != 0:\n            result = num1 / num2\n        else:\n            print("Cannot divide by zero!")\n            return\n    else:\n        print("Invalid operator")\n        return\n\n    print(f"Result: {num1} {operator} {num2} = {result}")\n\ncalculator()\n\nPROJECT 2: STUDENT GRADE TRACKER\n\nstudents = {}\n\ndef add_student(name, grade):\n    students[name] = grade\n    print(f"{name} added with grade {grade}")\n\ndef get_average():\n    if not students:\n        return 0\n    return sum(students.values()) / len(students)\n\nadd_student("Amara", 85)\nadd_student("Kwame", 92)\nadd_student("Fatima", 78)\n\nprint(f"Class average: {get_average():.1f}")\nprint(f"All students: {students}")\n\nPROJECT 3: TO-DO LIST\n\ntodos = []\n\ndef add_task(task):\n    todos.append({"task": task, "done": False})\n\ndef complete_task(index):\n    todos[index]["done"] = True\n\ndef show_tasks():\n    for i, todo in enumerate(todos):\n        status = "DONE" if todo["done"] else "PENDING"\n        print(f"{i+1}. [{status}] {todo[\'task\']}")\n\nadd_task("Learn Python")\nadd_task("Build a project")\nadd_task("Apply for jobs")\ncomplete_task(0)\nshow_tasks()' },
  ]);
  await addQuizzes(db, [
    { moduleId: pyIds[0], question: 'Which function is used to display output in Python?', options: ['console.log()', 'echo()', 'print()', 'display()'], correct: 2, explanation: 'print() is the Python function used to display output to the screen.' },
    { moduleId: pyIds[0], question: 'What data type is the value True in Python?', options: ['String', 'Integer', 'Boolean', 'Float'], correct: 2, explanation: 'True and False are Boolean values in Python.' },
    { moduleId: pyIds[1], question: 'What does the range(5) function produce?', options: ['1, 2, 3, 4, 5', '0, 1, 2, 3, 4', '0, 1, 2, 3, 4, 5', '1, 2, 3, 4'], correct: 1, explanation: 'range(5) produces numbers 0, 1, 2, 3, 4 (starts at 0, stops before 5).' },
    { moduleId: pyIds[2], question: 'Which method adds an item to the end of a Python list?', options: ['add()', 'insert()', 'append()', 'push()'], correct: 2, explanation: 'The append() method adds an item to the end of a list.' },
  ]);

  // ── COURSE 5: Digital Marketing ────────────────────────────────────────────
  const mktIds = await addModules(db, courses[4].id, [
    { title: 'Introduction to Digital Marketing', order_index: 1, duration_minutes: 40, content: 'INTRODUCTION TO DIGITAL MARKETING\n\nDigital marketing is promoting products or services using the internet and digital devices.\n\nWHY DIGITAL MARKETING?\n- Reach millions of people at low cost\n- Target specific audiences precisely\n- Measure results in real time\n- Compete with large companies\n\nDIGITAL MARKETING CHANNELS:\n\n1. SEARCH ENGINE OPTIMIZATION (SEO)\nGet your website to appear at the top of Google search results.\nFree but takes time.\n\n2. SOCIAL MEDIA MARKETING\nUse platforms like Instagram, Facebook, TikTok to reach customers.\nCan be free (organic) or paid (ads).\n\n3. EMAIL MARKETING\nSend targeted emails to subscribers.\nHighest ROI of all channels.\n\n4. CONTENT MARKETING\nCreate blogs, videos, podcasts that attract customers.\nBuilds trust and authority.\n\n5. PAY-PER-CLICK ADVERTISING (PPC)\nPay for ads on Google or social media.\nFast results but costs money.\n\n6. INFLUENCER MARKETING\nPartner with social media influencers to promote your brand.\n\nTHE DIGITAL MARKETING FUNNEL:\nAWARENESS → INTEREST → CONSIDERATION → PURCHASE → LOYALTY\n\nKEY METRICS TO TRACK:\n- Reach: How many people saw your content\n- Engagement: Likes, comments, shares\n- Click-through rate (CTR): % who clicked your link\n- Conversion rate: % who took the desired action\n- Return on investment (ROI): Profit vs cost' },
    { title: 'Social Media Strategy', order_index: 2, duration_minutes: 50, content: 'SOCIAL MEDIA STRATEGY\n\nA social media strategy is a plan for how you will use social platforms to achieve your goals.\n\nCHOOSING THE RIGHT PLATFORMS:\n\nINSTAGRAM:\n- Best for: Visual products, fashion, food, travel, lifestyle\n- Audience: 18-34 year olds\n- Content: Photos, Reels, Stories\n\nFACEBOOK:\n- Best for: Local businesses, events, community groups\n- Audience: 25-55 year olds\n- Content: Posts, videos, ads, groups\n\nTIKTOK:\n- Best for: Entertainment, youth brands, viral content\n- Audience: 16-24 year olds\n- Content: Short videos (15-60 seconds)\n\nLINKEDIN:\n- Best for: B2B, professional services, job seekers\n- Audience: Professionals 25-45\n- Content: Articles, career updates, industry news\n\nCREATING A CONTENT CALENDAR:\n1. Decide how often to post (e.g., 3x per week)\n2. Plan content themes for each day\n3. Create content in batches\n4. Schedule posts in advance\n5. Engage with comments and messages\n\nCONTENT IDEAS:\n- Behind the scenes\n- Customer testimonials\n- Tips and tutorials\n- Product showcases\n- Questions and polls\n- Industry news\n\nHASHTAG STRATEGY:\n- Use 5-15 relevant hashtags\n- Mix popular and niche hashtags\n- Create a branded hashtag\n- Research what competitors use' },
    { title: 'SEO & Content Marketing', order_index: 3, duration_minutes: 45, content: 'SEO AND CONTENT MARKETING\n\nSEO (Search Engine Optimization) helps people find you on Google.\n\nHOW GOOGLE RANKS WEBSITES:\n1. Relevance: Does your content match the search?\n2. Authority: Do other sites link to you?\n3. User experience: Is your site fast and easy to use?\n\nON-PAGE SEO:\n- Use keywords in your title, headings, and content\n- Write descriptive meta descriptions\n- Use alt text for images\n- Create clear URL structures\n- Make sure your site loads fast\n\nKEYWORD RESEARCH:\n1. Think about what your customers search for\n2. Use Google\'s autocomplete suggestions\n3. Check "People also ask" on Google\n4. Use free tools: Google Keyword Planner, Ubersuggest\n\nCONTENT MARKETING STRATEGY:\n\nTYPES OF CONTENT:\n- Blog posts: Educate and attract organic traffic\n- Videos: Engage and explain complex topics\n- Infographics: Visualize data and processes\n- Podcasts: Build audience while they commute\n- Ebooks/Guides: Generate leads\n\nCONTENT CREATION TIPS:\n- Solve a specific problem for your audience\n- Use clear, simple language\n- Include images and examples\n- Add a call-to-action (what should readers do next?)\n- Publish consistently\n\nMEASURING SUCCESS:\n- Google Analytics: Track website visitors\n- Google Search Console: Track search rankings\n- Social media insights: Track engagement\n- Email open rates and click rates' },
  ]);
  await addQuizzes(db, [
    { moduleId: mktIds[0], question: 'Which digital marketing channel has the highest ROI?', options: ['Social media ads', 'Email marketing', 'TV commercials', 'Billboard ads'], correct: 1, explanation: 'Email marketing consistently delivers the highest return on investment of all digital marketing channels.' },
    { moduleId: mktIds[1], question: 'Which platform is best for reaching professional B2B audiences?', options: ['TikTok', 'Instagram', 'LinkedIn', 'Snapchat'], correct: 2, explanation: 'LinkedIn is the leading professional network, ideal for B2B marketing and professional services.' },
    { moduleId: mktIds[2], question: 'What does SEO stand for?', options: ['Social Engagement Optimization', 'Search Engine Optimization', 'Site Experience Online', 'Search Experience Operations'], correct: 1, explanation: 'SEO stands for Search Engine Optimization - the practice of improving your website to rank higher in search results.' },
  ]);

  // ── COURSE 6: Data Analysis ────────────────────────────────────────────────
  const dataIds = await addModules(db, courses[5].id, [
    { title: 'Introduction to Data Analysis', order_index: 1, duration_minutes: 35, content: 'INTRODUCTION TO DATA ANALYSIS\n\nData analysis is the process of examining data to find useful information and make decisions.\n\nWHY DATA ANALYSIS MATTERS:\n- Businesses use data to make better decisions\n- Helps identify trends and patterns\n- Reduces guesswork\n- High demand skill in the job market\n\nTHE DATA ANALYSIS PROCESS:\n1. DEFINE THE QUESTION\nWhat do you want to find out?\nExample: "Which products sell best on weekends?"\n\n2. COLLECT DATA\nGather relevant data from reliable sources.\nSources: Surveys, databases, sales records, social media\n\n3. CLEAN THE DATA\nRemove errors, duplicates, and incomplete entries.\nThis is often 80% of the work!\n\n4. ANALYZE THE DATA\nUse formulas, charts, and statistics to find patterns.\n\n5. VISUALIZE THE DATA\nCreate charts and graphs to communicate findings.\n\n6. DRAW CONCLUSIONS\nWhat does the data tell you? What actions should be taken?\n\nTYPES OF DATA:\n- Quantitative: Numbers (sales figures, age, temperature)\n- Qualitative: Categories (gender, product type, country)\n- Time series: Data over time (monthly sales, daily visitors)\n\nCOMMON DATA ANALYSIS TOOLS:\n- Excel / Google Sheets (beginner)\n- Python with Pandas (intermediate)\n- Tableau / Power BI (visualization)\n- SQL (database queries)' },
    { title: 'Excel & Google Sheets Essentials', order_index: 2, duration_minutes: 55, content: 'EXCEL AND GOOGLE SHEETS ESSENTIALS\n\nSpreadsheets are the most widely used data analysis tools in business.\n\nKEY CONCEPTS:\n\nCELLS, ROWS, AND COLUMNS:\n- Cells are identified by column letter + row number (A1, B2, C3)\n- Rows go horizontally (1, 2, 3...)\n- Columns go vertically (A, B, C...)\n\nESSENTIAL FORMULAS:\n\nSUM: Add numbers\n=SUM(A1:A10)  adds all values from A1 to A10\n\nAVERAGE: Calculate mean\n=AVERAGE(B1:B10)\n\nCOUNT: Count cells with numbers\n=COUNT(C1:C10)\n\nCOUNTIF: Count cells meeting a condition\n=COUNTIF(D1:D10, "Yes")  counts cells containing "Yes"\n\nIF: Conditional logic\n=IF(A1>50, "Pass", "Fail")  returns Pass if A1 > 50\n\nVLOOKUP: Look up values in a table\n=VLOOKUP(lookup_value, table_range, column_number, FALSE)\n\nMAX and MIN:\n=MAX(A1:A10)  largest value\n=MIN(A1:A10)  smallest value\n\nPIVOT TABLES:\nPivot tables summarize large datasets quickly.\n1. Select your data\n2. Insert > Pivot Table\n3. Drag fields to Rows, Columns, Values\n4. Instantly see summaries and totals\n\nCHARTS AND GRAPHS:\n- Bar chart: Compare categories\n- Line chart: Show trends over time\n- Pie chart: Show proportions\n- Scatter plot: Show relationships between variables\n\nDATA CLEANING TIPS:\n- Remove duplicate rows\n- Fix inconsistent formatting (dates, names)\n- Fill in or remove blank cells\n- Standardize text (uppercase/lowercase)' },
    { title: 'Data Visualization & Reporting', order_index: 3, duration_minutes: 45, content: 'DATA VISUALIZATION AND REPORTING\n\nData visualization turns numbers into visual stories that anyone can understand.\n\nWHY VISUALIZATION MATTERS:\n- Humans process visuals 60,000x faster than text\n- Makes complex data easy to understand\n- Helps decision makers act quickly\n- Makes your reports more professional\n\nCHOOSING THE RIGHT CHART:\n\nBAR CHART:\nUse when: Comparing values across categories\nExample: Sales by product, revenue by region\n\nLINE CHART:\nUse when: Showing change over time\nExample: Monthly website visitors, daily temperature\n\nPIE CHART:\nUse when: Showing parts of a whole (use sparingly)\nExample: Market share, budget breakdown\nRule: Use only when you have 5 or fewer categories\n\nSCATTER PLOT:\nUse when: Showing relationship between two variables\nExample: Advertising spend vs sales revenue\n\nHEATMAP:\nUse when: Showing patterns in a matrix of data\nExample: Website clicks by hour and day\n\nDATA STORYTELLING:\n1. Start with the key insight (the "so what")\n2. Provide context (why does this matter?)\n3. Show the data that supports your point\n4. End with a recommendation or action\n\nREPORT STRUCTURE:\n- Executive Summary: Key findings in 3-5 bullet points\n- Background: Why was this analysis done?\n- Methodology: How was data collected and analyzed?\n- Findings: What did the data show?\n- Recommendations: What should be done?\n\nBEST PRACTICES:\n- Keep charts simple and uncluttered\n- Always label axes and include units\n- Use consistent colors throughout\n- Highlight the most important data point\n- Include the data source' },
  ]);
  await addQuizzes(db, [
    { moduleId: dataIds[0], question: 'What is the first step in the data analysis process?', options: ['Collect data', 'Define the question', 'Clean the data', 'Create charts'], correct: 1, explanation: 'You must first define what question you are trying to answer before collecting or analyzing any data.' },
    { moduleId: dataIds[1], question: 'Which Excel formula calculates the average of a range?', options: ['=SUM()', '=COUNT()', '=AVERAGE()', '=MEAN()'], correct: 2, explanation: '=AVERAGE() calculates the arithmetic mean of a range of cells.' },
    { moduleId: dataIds[2], question: 'Which chart type is best for showing change over time?', options: ['Pie chart', 'Bar chart', 'Line chart', 'Scatter plot'], correct: 2, explanation: 'Line charts are ideal for showing trends and changes over time.' },
  ]);

  // ── OPPORTUNITIES ──────────────────────────────────────────────────────────
  const oppData = [
    { employer: employer1Id, title: 'Junior Web Developer', company: 'TechAfrica Ltd', desc: 'Join our team building web applications for African businesses. Great opportunity to learn and grow!', type: 'job', location: 'Nairobi, Kenya', remote: 0, salary: '$500-$800/month', skills: ['HTML', 'CSS', 'JavaScript'], courses: [courses[0].id], deadline: '2026-06-30' },
    { employer: employer1Id, title: 'Python Developer Intern', company: 'TechAfrica Ltd', desc: 'Join our data team building pipelines and automation scripts. Perfect for recent graduates.', type: 'internship', location: 'Nairobi, Kenya', remote: 1, salary: 'Stipend: $200/month', skills: ['Python', 'Data Analysis'], courses: [courses[3].id], deadline: '2026-07-31' },
    { employer: employer2Id, title: 'Graphic Design Intern', company: 'Creative Hub', desc: 'Support our creative team on branding projects and social media content.', type: 'internship', location: 'Accra, Ghana', remote: 0, salary: 'Stipend: $150/month', skills: ['Figma', 'Design', 'Branding'], courses: [courses[1].id], deadline: '2026-06-15' },
    { employer: employer2Id, title: 'Social Media Manager', company: 'Creative Hub', desc: 'Manage clients online presence, create content calendars, and analyze performance metrics.', type: 'job', location: 'Accra, Ghana', remote: 1, salary: '$400-$600/month', skills: ['Social Media', 'Content', 'Marketing'], courses: [courses[4].id], deadline: '2026-07-01' },
    { employer: employer1Id, title: 'Business Development Volunteer', company: 'TechAfrica Ltd', desc: 'Help expand our reach across Africa through market research and proposals.', type: 'volunteer', location: 'Remote', remote: 1, salary: 'Unpaid (Certificate provided)', skills: ['Business Planning', 'Research'], courses: [courses[2].id], deadline: '2026-08-01' },
    { employer: employer2Id, title: 'Data Analyst Intern', company: 'Creative Hub', desc: 'Analyze campaign performance data and create reports for our clients using Excel and Google Sheets.', type: 'internship', location: 'Accra, Ghana', remote: 1, salary: 'Stipend: $180/month', skills: ['Data', 'Excel', 'Analytics'], courses: [courses[5].id], deadline: '2026-07-15' },
  ];

  for (const o of oppData) {
    await db.run('INSERT INTO opportunities (id, employer_id, title, company, description, type, location, is_remote, salary_range, required_skills, required_courses, deadline) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
      [uuidv4(), o.employer, o.title, o.company, o.desc, o.type, o.location, o.remote, o.salary, JSON.stringify(o.skills), JSON.stringify(o.courses), o.deadline]);
  }

  // ── ASSIGNMENTS (one per module, 18 total) ─────────────────────────────────
  // Web Development
  await addAssignment(db, webIds[0], courses[0].id, 'Build Your First HTML Page', 'Create a complete HTML page about yourself.', 'Create an HTML page that includes:\n1. Proper DOCTYPE and html/head/body structure\n2. A title tag with your name\n3. An h1 heading with your name\n4. A paragraph about yourself (at least 3 sentences)\n5. An unordered list of 5 hobbies\n6. A link to your favourite website\n7. At least one image\n\nPaste your complete HTML code in the submission box.');
  await addAssignment(db, webIds[1], courses[0].id, 'Style Your Page with CSS', 'Add CSS styling to your HTML page from the previous module.', 'Add a style section to your HTML page and:\n1. Set a background color for the body\n2. Style your h1 with a custom color and font size\n3. Style paragraphs with readable line spacing (1.6)\n4. Add padding and a border-radius to your list\n5. Add one media query for screens smaller than 600px\n\nPaste your complete HTML + CSS code below.');
  await addAssignment(db, webIds[2], courses[0].id, 'Add JavaScript Interactivity', 'Make your webpage interactive with JavaScript.', 'Add JavaScript to your page to:\n1. A button that changes the background color when clicked\n2. A form that greets the user by name when submitted\n3. A click counter that shows how many times a button was clicked\n4. One additional interactive feature of your choice\n\nPaste your complete HTML + CSS + JavaScript code below.');

  // Graphic Design
  await addAssignment(db, designIds[0], courses[1].id, 'Design Principles Analysis', 'Analyze a real-world design using the 5 core principles.', 'Choose any logo, poster, or website you find visually appealing.\n\n1. Name the design and where you found it\n2. Identify how CONTRAST is used (give a specific example)\n3. Identify how ALIGNMENT is used\n4. Identify how REPETITION is used\n5. Identify how PROXIMITY is used\n6. Comment on the use of WHITE SPACE\n7. Overall: What makes this design effective?\n\nWrite at least 200 words in your submission.');
  await addAssignment(db, designIds[1], courses[1].id, 'Create a Color Palette', 'Design a professional color palette for a fictional brand.', 'Create a color palette for a fictional African tech startup called "SavannaHub".\n\n1. Choose a primary brand color and explain why (psychology)\n2. Choose 2 complementary or analogous colors\n3. Add 2 neutral colors\n4. For each color, write the hex code (e.g. #2563eb)\n5. Explain what emotion or message each color communicates\n6. Choose 2 font pairings for the brand and explain your choice\n\nExample format:\nPrimary: #2563eb (Blue) - communicates trust and technology\nSecondary: #f59e0b (Amber) - communicates energy and innovation\n...');
  await addAssignment(db, designIds[2], courses[1].id, 'Design a Logo Concept', 'Create a logo concept for a fictional business.', 'Design a logo concept for a fictional business of your choice.\n\n1. State the business name and what it does\n2. Choose the logo type (wordmark, lettermark, symbol, combination, or emblem) and explain why\n3. Describe the visual concept in detail (shapes, symbols, style)\n4. Explain your color choice and what it communicates\n5. Explain your font choice\n6. Describe how the logo would look in black and white\n7. If you have access to Canva or any design tool, attach a link to your design\n\nWrite at least 150 words describing your concept.');

  // Entrepreneurship
  await addAssignment(db, bizIds[0], courses[2].id, 'Identify a Business Opportunity', 'Find a real problem in your community and propose a business solution.', 'Look around your community and identify a real problem that a business could solve.\n\n1. Describe the problem clearly (who has it, how often, how painful is it?)\n2. Describe your proposed business solution\n3. Who are your target customers? (age, location, income level)\n4. How would you make money? (pricing model)\n5. Run the validation test:\n   - Is this a real problem? (Yes/No + explanation)\n   - Will people pay for it? (Yes/No + explanation)\n   - Is the market big enough? (estimate number of potential customers)\n   - Can you realistically build this? (Yes/No + explanation)\n6. Rate your idea 1-10 and explain your rating\n\nWrite at least 250 words.');
  await addAssignment(db, bizIds[1], courses[2].id, 'Write a Mini Business Plan', 'Create a one-page business plan for your business idea.', 'Using the business idea from the previous assignment, write a mini business plan with these sections:\n\n1. BUSINESS NAME AND TAGLINE\n2. PROBLEM AND SOLUTION (2-3 sentences each)\n3. TARGET MARKET (describe your ideal customer in detail)\n4. PRODUCT/SERVICE (what exactly are you selling?)\n5. REVENUE MODEL (how will you make money?)\n6. MARKETING STRATEGY (3 specific ways you will attract customers)\n7. STARTUP COSTS (list at least 5 costs with estimated amounts)\n8. YEAR 1 REVENUE GOAL (how much do you want to make in year 1?)\n\nBe specific and realistic. Write at least 300 words total.');
  await addAssignment(db, bizIds[2], courses[2].id, 'Create a Marketing Plan', 'Develop a 30-day social media marketing plan for your business.', 'Create a 30-day social media marketing plan for your business.\n\n1. Choose 2 social media platforms and explain why they suit your business\n2. Define your target audience on each platform\n3. Create a content calendar for Week 1 (7 days, at least 3 posts per week):\n   - Day, Platform, Content Type, Topic/Caption idea\n4. Write 3 sample social media posts in full (caption + hashtags)\n5. Define 2 key metrics you will track and why\n6. Set a 30-day goal (e.g. 500 followers, 100 website visits)\n\nBe creative and specific to your business.');

  // Python
  await addAssignment(db, pyIds[0], courses[3].id, 'Python Variables and Data Types', 'Write a Python program using variables and data types.', 'Write a Python program that:\n\n1. Creates variables for: your name (string), age (integer), height in meters (float), and whether you are a student (boolean)\n2. Prints each variable with a descriptive label\n   Example: print("Name:", name)\n3. Performs and prints 3 mathematical calculations using your age and height\n4. Creates a list of 5 of your favourite foods and prints the list\n5. Creates a dictionary with at least 4 facts about yourself and prints each key-value pair\n6. Uses at least 3 string methods on your name variable\n\nPaste your complete Python code and the output below.');
  await addAssignment(db, pyIds[1], courses[3].id, 'Build a Number Guessing Game', 'Create an interactive number guessing game using Python.', 'Build a number guessing game in Python:\n\n1. The program picks a random number between 1 and 100\n   (use: import random; number = random.randint(1, 100))\n2. The user has 7 attempts to guess the number\n3. After each wrong guess, tell the user if their guess is too HIGH or too LOW\n4. If they guess correctly, congratulate them and show how many attempts it took\n5. If they run out of attempts, reveal the correct number\n6. After the game ends, ask if they want to play again\n\nBonus: Keep track of the best score (fewest guesses) across multiple games.\n\nPaste your complete code and a sample game output below.');
  await addAssignment(db, pyIds[2], courses[3].id, 'Build a Contact Book App', 'Create a command-line contact book application.', 'Build a contact book application in Python with these features:\n\n1. ADD a contact (name, phone, email)\n2. VIEW all contacts\n3. SEARCH for a contact by name\n4. DELETE a contact\n5. A menu that keeps running until the user chooses to exit\n\nRequirements:\n- Store contacts in a dictionary or list of dictionaries\n- Use functions for each feature\n- Handle the case where a contact is not found\n- Show a numbered menu to the user\n\nExample menu:\n1. Add contact\n2. View all contacts\n3. Search contact\n4. Delete contact\n5. Exit\n\nPaste your complete code and a sample run showing all features.');

  // Digital Marketing
  await addAssignment(db, mktIds[0], courses[4].id, 'Digital Marketing Audit', 'Analyze the digital marketing presence of a local business.', 'Choose a local business in your area (or a small African business online) and audit their digital marketing.\n\n1. Business name and what they sell\n2. WEBSITE: Do they have one? Is it mobile-friendly? What could be improved?\n3. SOCIAL MEDIA: Which platforms are they on? How often do they post? What is their engagement like?\n4. SEO: Search for their business on Google. Do they appear? What keywords could they target?\n5. EMAIL MARKETING: Do they collect emails? Do they send newsletters?\n6. OVERALL SCORE: Rate their digital marketing 1-10\n7. TOP 3 RECOMMENDATIONS: What should they do first to improve?\n\nWrite at least 250 words with specific observations.');
  await addAssignment(db, mktIds[1], courses[4].id, 'Create a Social Media Content Plan', 'Develop a 2-week social media content plan for a business.', 'Choose a business (real or fictional) and create a 2-week social media content plan.\n\n1. Business description (name, product/service, target audience)\n2. Platform choice: Choose 2 platforms and justify your choice\n3. Content calendar for 2 weeks:\n   - Date | Platform | Content Type | Topic | Caption (brief)\n   - Post at least 3 times per week on each platform\n4. Write 2 complete posts in full detail:\n   - Full caption text\n   - Hashtags (10-15)\n   - Description of the image or video\n5. Define your engagement strategy (how will you respond to comments?)\n\nBe specific and creative.');
  await addAssignment(db, mktIds[2], courses[4].id, 'SEO Keyword Research', 'Conduct keyword research for a business website.', 'Conduct keyword research for a fictional business: "AfriCraft - handmade African jewellery sold online".\n\n1. List 10 keywords potential customers might search for\n2. Categorize them as: Short-tail (1-2 words) or Long-tail (3+ words)\n3. For each keyword, estimate: High/Medium/Low search volume and competition\n4. Choose your TOP 3 keywords and explain why\n5. Write a sample blog post title and meta description (160 characters max) using your top keyword\n6. Suggest 3 blog post topics that would attract organic traffic\n7. Name 2 free tools you would use for keyword research and explain how\n\nWrite at least 200 words.');

  // Data Analysis
  await addAssignment(db, dataIds[0], courses[5].id, 'Data Analysis Case Study', 'Analyze a real-world dataset and draw conclusions.', 'A small shop recorded their daily sales for 2 weeks. Analyze this data:\n\nWeek 1: Mon=150, Tue=200, Wed=180, Thu=220, Fri=350, Sat=420, Sun=300\nWeek 2: Mon=160, Tue=190, Wed=210, Thu=240, Fri=380, Sat=450, Sun=320\n\nAnswer these questions:\n1. What was the total sales for each week?\n2. What was the average daily sales for each week?\n3. Which day had the highest sales overall?\n4. Which day had the lowest sales overall?\n5. What was the percentage increase from Week 1 to Week 2?\n6. What trend do you notice about weekday vs weekend sales?\n7. Based on this data, give 2 business recommendations to the shop owner\n8. What additional data would you want to collect to do a better analysis?\n\nShow all your calculations.');
  await addAssignment(db, dataIds[1], courses[5].id, 'Build a Sales Dashboard', 'Create a spreadsheet dashboard to track and visualize sales data.', 'Create a Google Sheets or Excel spreadsheet with the following:\n\n1. A data table with at least 20 rows of fictional sales data including:\n   - Date, Product Name, Category, Units Sold, Unit Price, Total Revenue\n2. Use formulas to calculate:\n   - Total revenue per row (=Units Sold * Unit Price)\n   - SUM of total revenue\n   - AVERAGE revenue per sale\n   - MAX and MIN sale values\n   - COUNTIF to count sales per category\n3. Create a Pivot Table summarizing revenue by category\n4. Create 2 charts:\n   - A bar chart showing revenue by product\n   - A line chart showing revenue over time\n5. Add a summary section at the top with key metrics\n\nShare a link to your Google Sheet or describe your spreadsheet in detail.');
  await addAssignment(db, dataIds[2], courses[5].id, 'Create a Data Story', 'Turn data into a compelling visual story.', 'You are a data analyst presenting findings to a business owner. Create a data story using this scenario:\n\nAn online store wants to understand why sales dropped 30% in March compared to February.\n\nYou have this data:\n- February: 500 orders, avg order value $45, top product: Phone Cases\n- March: 350 orders, avg order value $42, top product: Phone Cases\n- Website traffic: Feb=8000 visits, Mar=7500 visits\n- Conversion rate: Feb=6.25%, Mar=4.67%\n- New customers: Feb=200, Mar=120\n- Returning customers: Feb=300, Mar=230\n\nYour data story must include:\n1. HEADLINE: One sentence summarizing the key finding\n2. CONTEXT: Why does this matter?\n3. ANALYSIS: What does the data show? (use the numbers)\n4. ROOT CAUSE: What likely caused the drop? (give 2-3 hypotheses)\n5. RECOMMENDATIONS: 3 specific actions the business should take\n6. What additional data would help confirm your hypothesis?\n\nWrite at least 300 words.');

  console.log('✅ Seed complete: 5 users, 6 courses, 18 modules, 22 quizzes, 18 assignments, 6 opportunities');
}

async function seed() {
  console.log('🌱 Seeding database...');
  const db = await getDb();
  await db.exec('DELETE FROM assignment_submissions; DELETE FROM assignments; DELETE FROM applications; DELETE FROM certificates; DELETE FROM module_progress; DELETE FROM enrollments; DELETE FROM quizzes; DELETE FROM modules; DELETE FROM opportunities; DELETE FROM courses; DELETE FROM notifications; DELETE FROM users;');
  await seedData(db);
  console.log('\n📋 Test Accounts:');
  console.log('  Admin:    admin@youthskills.com / password123');
  console.log('  Youth:    amara@example.com / password123');
  console.log('  Employer: hr@techafrica.com / password123');
  process.exit(0);
}

module.exports = { seedData };

if (require.main === module) {
  seed().catch(err => { console.error(err); process.exit(1); });
}
